services:
  web:
    image: java:v1
    container_name: javacon
    ports:
      - "5000:8080"
    depends_on:
      - mongo
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongo:27017/dev

  mongo:
    image: mongo:v1
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: